### ISSUE TITLE
Your thoughts on autocompletion

### ISSUE THREAD

**Issue by frou** [evancz/elm-syntax-highlighting#3]
From the description of your workflow here, it seems clear that you don't place the same value on language-aware autocompletion that a lot of programmers do. Do you remember if you've elaborated on this anywhere?

**Comment by evancz** [comment]
There has been an outline of "type directed autocomplete" [here](https://github.com/elm/projects#type-directed-autocomplete) since [2017](https://github.com/elm/projects/commit/17031d86ba0ed63c04bd55de5d51b408420510ec#diff-04c6e90faac2675aa89e2176d2eec7d8).

The main concern when it comes to editor plugins is making sure that features are implemented efficiently and reliably. This particular plugin never had something like type directed autocompletion as far as I know, and I want to stick to features that can be done really well.
